spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.MultipartAutoConfiguration
  servlet:
    multipart:
      resolve-lazily: false
  main:
    allow-bean-definition-overriding: true